using Godot;

namespace TheHaunt.UI;

/// <summary>
/// The item-icon atlas: assets/sprites/icons/items.png, one 12x12 icon per item in a
/// single row, generated by tools/gen_item_icons.py (rerun it when an item is added).
/// <see cref="Order"/> mirrors the generator's ITEMS table — which itself follows
/// ItemDefs.All insertion order. Two guards hold the three lists together: IconTests
/// pins Order to ItemDefs.All and the atlas dimensions to Order, and the generator
/// refuses to write unless its ITEMS ids match Order in order (and its colors match
/// ItemDefs) — so a drift fails at test time or authoring time, never on screen.
/// Unknown ids return null: the caller keeps its '?' placeholder path (unknown ids
/// render, never dropped).
/// </summary>
public static class ItemIcons
{
    public const string SheetPath = "res://assets/sprites/icons/items.png";
    public const int Size = 12;

    /// <summary>Atlas column per item id — gen_item_icons.py's ITEMS order, verbatim.</summary>
    public static readonly IReadOnlyList<string> Order = new[]
    {
        "hoe", "watering_can", "scythe", "axe", "pick",
        "turnip_seeds", "greenbean_seeds", "potato_seeds", "cauliflower_seeds",
        "turnip", "greenbean", "potato", "cauliflower",
        "lumber", "stone",
    };

    private static readonly Dictionary<string, AtlasTexture> Cache = new();
    private static Texture2D? _sheet;

    public static Texture2D? For(string itemId)
    {
        if (Cache.TryGetValue(itemId, out AtlasTexture? cached))
        {
            return cached;
        }
        int column = -1;
        for (int i = 0; i < Order.Count; i++)
        {
            if (Order[i] == itemId)
            {
                column = i;
                break;
            }
        }
        if (column < 0)
        {
            return null;
        }
        _sheet ??= GD.Load<Texture2D>(SheetPath)
            ?? throw new InvalidOperationException($"Missing item icon atlas at {SheetPath}.");
        var texture = new AtlasTexture
        {
            Atlas = _sheet,
            Region = new Rect2(column * Size, 0, Size, Size),
        };
        Cache[itemId] = texture;
        return texture;
    }
}
