"""The live flight panel: a Text datablock the build puts in the .blend
(`flyover_flights.py`). Kevin opens it in Blender's Text Editor and presses Run Script
(or trusts the file: it is a registered module, so auto-run loads it): the 3D View's
sidebar (N) gets a "Flyover" tab --

  View <flight>          the scene, camera, frame range and markers of that flight; the
                         viewport through its camera, Solid, leaf cards hidden, frame-drop
                         playback (flight.switch)
  Rebake this flight     re-read tools/flyover/flights/<flight>.py and re-plan, check and
                         bake that camera in seconds, no world rebuild (flight.rebake);
                         the flown table + any clearance problems go to the Text
                         `flyover_rebake_report` (and the console)
  Playblast (viewport)   the viewport through the camera, every frame, to
                         out/playblast_<flight>_live.mp4 (bpy.ops.render.opengl; blocks
                         the UI while it runs)
"""

import os

PKG_DIR = os.path.dirname(os.path.abspath(__file__))
TEXT_NAME = "flyover_flights.py"

SCRIPT = r'''# Flyover flights: Run Script, then 3D View sidebar (N) -> "Flyover" tab.
# Generated by tools/flyover/flight_panel.py (a rebuild replaces this text).
import importlib
import sys

import bpy

PKG = __PKG__
if PKG not in sys.path:
    sys.path.insert(0, PKG)


def _flight():
    import flight
    return importlib.reload(flight)


def _names():
    import flights
    return importlib.reload(flights).NAMES


class FLYOVER_OT_switch_flight(bpy.types.Operator):
    """View this flight: its scene, camera and frame range, the viewport through the camera"""
    bl_idname = "flyover.switch_flight"
    bl_label = "View flight"
    name: bpy.props.StringProperty()

    def execute(self, context):
        _flight().switch(self.name)
        return {"FINISHED"}


class FLYOVER_OT_rebake_flight(bpy.types.Operator):
    """Re-read flights/<flight>.py and rebake the active scene's flight camera"""
    bl_idname = "flyover.rebake_flight"
    bl_label = "Rebake this flight"

    def execute(self, context):
        fl, bad = _flight().rebake(context.scene.get("flyover_flight"))
        msg = f"{fl.name}: {fl.n} frames ({fl.n / fl.fps:.1f} s); " + (
            f"{len(bad)} CLEARANCE problems: see the text flyover_rebake_report" if bad else "every frame clear")
        self.report({"WARNING"} if bad else {"INFO"}, msg)
        return {"FINISHED"}


class FLYOVER_OT_playblast(bpy.types.Operator):
    """Render the viewport through the flight camera to out/playblast_<flight>_live.mp4"""
    bl_idname = "flyover.playblast"
    bl_label = "Playblast (viewport)"

    def execute(self, context):
        path = _flight().viewport_playblast(context)
        self.report({"INFO"}, f"playblast: {path}")
        return {"FINISHED"}


class FLYOVER_PT_flights(bpy.types.Panel):
    bl_space_type = "VIEW_3D"
    bl_region_type = "UI"
    bl_category = "Flyover"
    bl_label = "Flights"

    def draw(self, context):
        col = self.layout.column(align=True)
        sc = context.scene
        col.label(text=f"Active: {sc.get('flyover_flight', '-')}  ({sc.frame_start}-{sc.frame_end})")
        for n in _names():
            col.operator("flyover.switch_flight", text=f"View {n}").name = n
        col.separator()
        col.operator("flyover.rebake_flight", icon="FILE_REFRESH")
        col.operator("flyover.playblast", icon="RENDER_ANIMATION")


CLASSES = (FLYOVER_OT_switch_flight, FLYOVER_OT_rebake_flight, FLYOVER_OT_playblast, FLYOVER_PT_flights)


def register():
    for c in CLASSES:
        old = getattr(bpy.types, c.__name__, None)
        if old is not None:
            bpy.utils.unregister_class(old)
        bpy.utils.register_class(c)


register()
'''


def install():
    """(Re)make the panel's Text datablock in the open file (tagged: a rebuild replaces it)."""
    import bpy

    import scene
    old = bpy.data.texts.get(TEXT_NAME)
    if old is not None:
        bpy.data.texts.remove(old)
    txt = scene.tag(bpy.data.texts.new(TEXT_NAME))
    txt.write(SCRIPT.replace("__PKG__", repr(PKG_DIR)))
    txt.use_module = True
    return txt
